In [ ]:
import pyarrow.parquet as pq
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from datetime import datetime, date, time
import os

In [ ]:

pq_root = '/data/workspace_files/pq'
csv_root = '/data/workspace_files/csv'
for file in os.listdir(csv_root):
    df = pd.read_csv(os.path.join(csv_root, file))
    df['ts_event'] = pd.to_datetime(df['ts_event']).dt.tz_convert('America/New_York')
    for col in df.columns:
        if df[col].dtype == 'float64':
            df[col] = df[col].astype('float32')
        elif df[col].dtype == 'int64':
            df[col] = df[col].astype('int32')
    df.to_parquet(os.path.join(pq_root, file.replace('.csv', '.parquet')))

In [ ]:
s = 'QQQ'

file_path = f'xnas-itch-20210101-20250205.ohlcv-1m.{s}.parquet'
volume_data = pq.read_table(file_path)
df = volume_data.to_pandas()

In [3]:
df

,ts_event,rtype,publisher_id,instrument_id,open,high,low,close,volume,symbol,ratio_dbuy,ratio_dsell,ratio_neutral,dVol,dVolBuy,dVolSell,buyVol,sellVol
0,2024-02-22 04:00:00-05:00,33,2,13340,434.239990,434.279999,434.140015,434.279999,5087,QQQ,0.349320,0.486342,0.164338,2.208780e+06,7.715708e+05,1.074223e+06,1776,2474
1,2024-02-22 04:01:00-05:00,33,2,13340,434.269989,434.440002,434.230011,434.429993,9538,QQQ,0.584827,0.143109,0.272064,4.142442e+06,2.422612e+06,5.928208e+05,5578,1364
2,2024-02-22 04:02:00-05:00,33,2,13340,434.450012,434.450012,434.070007,434.070007,2781,QQQ,0.197744,0.286263,0.515992,1.207501e+06,2.387765e+05,3.456635e+05,549,796
3,2024-02-22 04:03:00-05:00,33,2,13340,434.040009,434.040009,433.700012,433.850006,567,QQQ,0.335083,0.620803,0.044114,2.459760e+05,8.242230e+04,1.527027e+05,189,351
4,2024-02-22 04:04:00-05:00,33,2,13340,433.940002,434.029999,433.940002,434.019989,2268,QQQ,0.060838,0.313062,0.626099,9.843072e+05,5.988372e+04,3.081495e+05,137,710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199218,2025-02-05 18:54:00-05:00,33,2,13340,527.059998,527.059998,527.059998,527.059998,2,QQQ,1.000000,0.000000,0.000000,1.054120e+03,1.054120e+03,0.000000e+00,2,0
199219,2025-02-05 18:55:00-05:00,33,2,13340,527.059998,527.059998,527.059998,527.059998,112,QQQ,1.000000,0.000000,0.000000,5.903072e+04,5.903072e+04,0.000000e+00,112,0
199220,2025-02-05 18:56:00-05:00,33,2,13340,527.090027,527.119995,527.090027,527.119995,300,QQQ,0.666656,0.333344,0.000000,1.581310e+05,1.054190e+05,5.271200e+04,199,100
199221,2025-02-05 18:57:00-05:00,33,2,13340,527.109985,527.109985,527.109985,527.109985,500,QQQ,0.000000,1.000000,0.000000,2.635550e+05,0.000000e+00,2.635550e+05,0,500
199222,2025-02-05 18:59:00-05:00,33,2,13340,527.109985,527.130005,527.109985,527.130005,11,QQQ,0.545445,0.000000,0.454555,5.798310e+03,3.162660e+03,0.000000e+00,5,0

                        ts_event  rtype  publisher_id  instrument_id  \
0      2024-02-22 04:00:00-05:00     33             2          13340
1      2024-02-22 04:01:00-05:00     33             2          13340
2      2024-02-22 04:02:00-05:00     33             2          13340
3      2024-02-22 04:03:00-05:00     33             2          13340
4      2024-02-22 04:04:00-05:00     33             2          13340
...                          ...    ...           ...            ...
199218 2025-02-05 18:54:00-05:00     33             2          13340
199219 2025-02-05 18:55:00-05:00     33             2          13340
199220 2025-02-05 18:56:00-05:00     33             2          13340
199221 2025-02-05 18:57:00-05:00     33             2          13340
199222 2025-02-05 18:59:00-05:00     33             2          13340

              open        high         low       close  volume symbol  \
0       434.239990  434.279999  434.140015  434.279999    5087    QQQ
1       434.269989  434.440002  434.230011  434.429993    9538    QQQ
2       434.450012  434.450012  434.070007  434.070007    2781    QQQ
3       434.040009  434.040009  433.700012  433.850006     567    QQQ
4       433.940002  434.029999  433.940002  434.019989    2268    QQQ
...            ...         ...         ...         ...     ...    ...
199218  527.059998  527.059998  527.059998  527.059998       2    QQQ
199219  527.059998  527.059998  527.059998  527.059998     112    QQQ
199220  527.090027  527.119995  527.090027  527.119995     300    QQQ
199221  527.109985  527.109985  527.109985  527.109985     500    QQQ
199222  527.109985  527.130005  527.109985  527.130005      11    QQQ

        ratio_dbuy  ratio_dsell  ratio_neutral          dVol       dVolBuy  \
0         0.349320     0.486342       0.164338  2.208780e+06  7.715708e+05
1         0.584827     0.143109       0.272064  4.142442e+06  2.422612e+06
2         0.197744     0.286263       0.515992  1.207501e+06  2.387765e+05
3         0.335083     0.620803       0.044114  2.459760e+05  8.242230e+04
4         0.060838     0.313062       0.626099  9.843072e+05  5.988372e+04
...            ...          ...            ...           ...           ...
199218    1.000000     0.000000       0.000000  1.054120e+03  1.054120e+03
199219    1.000000     0.000000       0.000000  5.903072e+04  5.903072e+04
199220    0.666656     0.333344       0.000000  1.581310e+05  1.054190e+05
199221    0.000000     1.000000       0.000000  2.635550e+05  0.000000e+00
199222    0.545445     0.000000       0.454555  5.798310e+03  3.162660e+03

            dVolSell  buyVol  sellVol
0       1.074223e+06    1776     2474
1       5.928208e+05    5578     1364
2       3.456635e+05     549      796
3       1.527027e+05     189      351
4       3.081495e+05     137      710
...              ...     ...      ...
199218  0.000000e+00       2        0
199219  0.000000e+00     112        0
199220  5.271200e+04     199      100
199221  2.635550e+05       0      500
199222  0.000000e+00       5        0

[199223 rows x 18 columns]

In [ ]:
df['ts_event'] = pd.to_datetime(df['ts_event']).dt.tz_convert('America/New_York')
for col in df.columns:
    if df[col].dtype == 'float64':
        df[col] = df[col].astype('float32')
    elif df[col].dtype == 'int64':
        df[col] = df[col].astype('int32')

In [197]:
df

,ts_event,rtype,publisher_id,instrument_id,open,high,low,close,volume,symbol,ratio_dbuy,ratio_dsell,ratio_neutral,dVol,dVolBuy,dVolSell,buyVol,sellVol
0,2024-02-22 04:00:00-05:00,33,2,13340,434.239990,434.279999,434.140015,434.279999,5087,QQQ,0.349320,0.486342,0.164338,2.208780e+06,7.715708e+05,1.074223e+06,1776,2474
1,2024-02-22 04:01:00-05:00,33,2,13340,434.269989,434.440002,434.230011,434.429993,9538,QQQ,0.584827,0.143109,0.272064,4.142442e+06,2.422612e+06,5.928208e+05,5578,1364
2,2024-02-22 04:02:00-05:00,33,2,13340,434.450012,434.450012,434.070007,434.070007,2781,QQQ,0.197744,0.286263,0.515992,1.207501e+06,2.387765e+05,3.456635e+05,549,796
3,2024-02-22 04:03:00-05:00,33,2,13340,434.040009,434.040009,433.700012,433.850006,567,QQQ,0.335083,0.620803,0.044114,2.459760e+05,8.242230e+04,1.527027e+05,189,351
4,2024-02-22 04:04:00-05:00,33,2,13340,433.940002,434.029999,433.940002,434.019989,2268,QQQ,0.060838,0.313062,0.626099,9.843072e+05,5.988372e+04,3.081495e+05,137,710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199218,2025-02-05 18:54:00-05:00,33,2,13340,527.059998,527.059998,527.059998,527.059998,2,QQQ,1.000000,0.000000,0.000000,1.054120e+03,1.054120e+03,0.000000e+00,2,0
199219,2025-02-05 18:55:00-05:00,33,2,13340,527.059998,527.059998,527.059998,527.059998,112,QQQ,1.000000,0.000000,0.000000,5.903072e+04,5.903072e+04,0.000000e+00,112,0
199220,2025-02-05 18:56:00-05:00,33,2,13340,527.090027,527.119995,527.090027,527.119995,300,QQQ,0.666656,0.333344,0.000000,1.581310e+05,1.054190e+05,5.271200e+04,199,100
199221,2025-02-05 18:57:00-05:00,33,2,13340,527.109985,527.109985,527.109985,527.109985,500,QQQ,0.000000,1.000000,0.000000,2.635550e+05,0.000000e+00,2.635550e+05,0,500
199222,2025-02-05 18:59:00-05:00,33,2,13340,527.109985,527.130005,527.109985,527.130005,11,QQQ,0.545445,0.000000,0.454555,5.798310e+03,3.162660e+03,0.000000e+00,5,0

                        ts_event  rtype  publisher_id  instrument_id  \
0      2024-02-22 04:00:00-05:00     33             2          13340
1      2024-02-22 04:01:00-05:00     33             2          13340
2      2024-02-22 04:02:00-05:00     33             2          13340
3      2024-02-22 04:03:00-05:00     33             2          13340
4      2024-02-22 04:04:00-05:00     33             2          13340
...                          ...    ...           ...            ...
199218 2025-02-05 18:54:00-05:00     33             2          13340
199219 2025-02-05 18:55:00-05:00     33             2          13340
199220 2025-02-05 18:56:00-05:00     33             2          13340
199221 2025-02-05 18:57:00-05:00     33             2          13340
199222 2025-02-05 18:59:00-05:00     33             2          13340

              open        high         low       close  volume symbol  \
0       434.239990  434.279999  434.140015  434.279999    5087    QQQ
1       434.269989  434.440002  434.230011  434.429993    9538    QQQ
2       434.450012  434.450012  434.070007  434.070007    2781    QQQ
3       434.040009  434.040009  433.700012  433.850006     567    QQQ
4       433.940002  434.029999  433.940002  434.019989    2268    QQQ
...            ...         ...         ...         ...     ...    ...
199218  527.059998  527.059998  527.059998  527.059998       2    QQQ
199219  527.059998  527.059998  527.059998  527.059998     112    QQQ
199220  527.090027  527.119995  527.090027  527.119995     300    QQQ
199221  527.109985  527.109985  527.109985  527.109985     500    QQQ
199222  527.109985  527.130005  527.109985  527.130005      11    QQQ

        ratio_dbuy  ratio_dsell  ratio_neutral          dVol       dVolBuy  \
0         0.349320     0.486342       0.164338  2.208780e+06  7.715708e+05
1         0.584827     0.143109       0.272064  4.142442e+06  2.422612e+06
2         0.197744     0.286263       0.515992  1.207501e+06  2.387765e+05
3         0.335083     0.620803       0.044114  2.459760e+05  8.242230e+04
4         0.060838     0.313062       0.626099  9.843072e+05  5.988372e+04
...            ...          ...            ...           ...           ...
199218    1.000000     0.000000       0.000000  1.054120e+03  1.054120e+03
199219    1.000000     0.000000       0.000000  5.903072e+04  5.903072e+04
199220    0.666656     0.333344       0.000000  1.581310e+05  1.054190e+05
199221    0.000000     1.000000       0.000000  2.635550e+05  0.000000e+00
199222    0.545445     0.000000       0.454555  5.798310e+03  3.162660e+03

            dVolSell  buyVol  sellVol
0       1.074223e+06    1776     2474
1       5.928208e+05    5578     1364
2       3.456635e+05     549      796
3       1.527027e+05     189      351
4       3.081495e+05     137      710
...              ...     ...      ...
199218  0.000000e+00       2        0
199219  0.000000e+00     112        0
199220  5.271200e+04     199      100
199221  2.635550e+05       0      500
199222  0.000000e+00       5        0

[199223 rows x 18 columns]

In [ ]:
def preprocess_data(df):
    df["date"] = df["ts_event"].dt.date
    df["time"] = df["ts_event"].dt.time  # Directly extract time from datetime
    
    df = df[(df['time'] >= pd.to_datetime('09:30').time()) & 
            (df['time'] <= pd.to_datetime('16:00').time())]
    
    return df

In [ ]:
df_processed = preprocess_data(df)

In [202]:
df_clean_15 = df_processed.set_index("ts_event")
df_clean_15 = df_clean_15.groupby('symbol').resample('15min', loffset=pd.Timedelta('15min')).sum(min_count=1).reset_index()
df_clean_15["date"] = df_clean_15["ts_event"].dt.date
df_clean_15["time"] = df_clean_15["ts_event"].dt.time

/var/folders/r5/gdkshdms0970h1kdrr8n5m1r0000gn/T/ipykernel_21150/2413817757.py:2: FutureWarning: 'loffset' in .resample() and in Grouper() is deprecated.

>>> df.resample(freq="3s", loffset="8H")

becomes:

>>> from pandas.tseries.frequencies import to_offset
>>> df = df.resample(freq="3s").mean()
>>> df.index = df.index.to_timestamp() + to_offset("8H")

  df_clean_15 = df_clean_15.groupby('symbol').resample('15min', loffset=pd.Timedelta('15min')).sum(min_count=1).reset_index()

In [ ]:
syms = df_clean_15['symbol'].unique()

In [ ]:
def is_time_between(check_time):
    begin_time, end_time = time(9,31), time(16,0)
    # If check time is not given, default to current UTC time
    check_time = check_time or datetime.utcnow().time()
    if begin_time < end_time:
        return check_time >= begin_time and check_time <= end_time

In [ ]:
df_clean_15["filter"] = df_clean_15.time.apply(is_time_between)
df_clean_15 = df_clean_15[df_clean_15["filter"] == True].dropna().reset_index()
df_clean_15 = df_clean_15.drop(["index","filter"],axis=1)

In [ ]:
df_clean_15 = df_clean_15.fillna(0)
df_clean_15.loc[df_clean_15["volume"] == 0, "volume"] = 1

In [14]:
plt.figure(figsize=(12, 6))  # Increase figure size

plt.plot(mean_volume['time'].astype(str), mean_volume['volume'], marker='o', linewidth=2)

plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.xlabel('Time of Day', fontsize=14)
plt.ylabel('Mean Trading Volume', fontsize=14)
plt.title('Intraday U-Shaped Trading Volume Pattern', fontsize=16)

plt.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.6)  # Lighter grid
plt.savefig("intraday_volume_plot.png", dpi=300, bbox_inches='tight')
plt.show()

,symbol,ts_event,rtype,publisher_id,instrument_id,open,high,low,close,volume,ratio_dbuy,ratio_dsell,ratio_neutral,dVol,dVolBuy,dVolSell,buyVol,sellVol,date,time
0,QQQ,2024-02-22 09:31:00-05:00,33.0,2.0,13340.0,434.489990,435.049988,434.320007,434.320007,412550.0,0.250785,0.198788,0.550426,179338752.0,44975496.0,35650468.0,103461.0,82010.0,2024-02-22,09:31:00
1,QQQ,2024-02-22 09:32:00-05:00,33.0,2.0,13340.0,434.299988,434.709991,433.850006,433.850006,109232.0,0.493689,0.464868,0.041442,47442292.0,23421754.0,22054416.0,53926.0,50778.0,2024-02-22,09:32:00
2,QQQ,2024-02-22 09:33:00-05:00,33.0,2.0,13340.0,433.850006,434.399994,433.730011,434.160004,122847.0,0.480586,0.451441,0.067973,53323212.0,25626386.0,24072264.0,59038.0,55458.0,2024-02-22,09:33:00
3,QQQ,2024-02-22 09:34:00-05:00,33.0,2.0,13340.0,434.179993,434.369995,433.750000,433.799988,82309.0,0.481281,0.486295,0.032423,35722984.0,17192804.0,17371922.0,39613.0,40026.0,2024-02-22,09:34:00
4,QQQ,2024-02-22 09:35:00-05:00,33.0,2.0,13340.0,433.809998,434.089996,433.720001,433.850006,86827.0,0.609997,0.325190,0.064813,37673172.0,22980508.0,12250956.0,52964.0,28235.0,2024-02-22,09:35:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93425,QQQ,2025-02-05 15:56:00-05:00,33.0,2.0,13340.0,525.940002,526.440002,525.940002,526.409973,41728.0,0.471466,0.350150,0.178384,21959392.0,10353100.0,7689091.0,19673.0,14611.0,2025-02-05,15:56:00
93426,QQQ,2025-02-05 15:57:00-05:00,33.0,2.0,13340.0,526.409973,526.630005,526.349976,526.609985,28778.0,0.350453,0.400345,0.249202,15151526.0,5309894.5,6065842.5,10085.0,11521.0,2025-02-05,15:57:00
93427,QQQ,2025-02-05 15:58:00-05:00,33.0,2.0,13340.0,526.609985,526.780029,526.609985,526.659973,57271.0,0.391810,0.355937,0.252253,30163432.0,11818339.0,10736282.0,22439.0,20384.0,2025-02-05,15:58:00
93428,QQQ,2025-02-05 15:59:00-05:00,33.0,2.0,13340.0,526.669983,526.919983,526.580017,526.900024,55642.0,0.465503,0.265581,0.268916,29309952.0,13643879.0,7784157.0,25901.0,14777.0,2025-02-05,15:59:00
93429,QQQ,2025-02-05 16:00:00-05:00,33.0,2.0,13340.0,526.890015,527.010010,526.729980,526.849976,137463.0,0.444601,0.310505,0.244894,72424272.0,32199934.0,22488080.0,61116.0,42682.0,2025-02-05,16:00:00

      symbol                  ts_event  rtype  publisher_id  instrument_id  \
0        QQQ 2024-02-22 09:31:00-05:00   33.0           2.0        13340.0
1        QQQ 2024-02-22 09:32:00-05:00   33.0           2.0        13340.0
2        QQQ 2024-02-22 09:33:00-05:00   33.0           2.0        13340.0
3        QQQ 2024-02-22 09:34:00-05:00   33.0           2.0        13340.0
4        QQQ 2024-02-22 09:35:00-05:00   33.0           2.0        13340.0
...      ...                       ...    ...           ...            ...
93425    QQQ 2025-02-05 15:56:00-05:00   33.0           2.0        13340.0
93426    QQQ 2025-02-05 15:57:00-05:00   33.0           2.0        13340.0
93427    QQQ 2025-02-05 15:58:00-05:00   33.0           2.0        13340.0
93428    QQQ 2025-02-05 15:59:00-05:00   33.0           2.0        13340.0
93429    QQQ 2025-02-05 16:00:00-05:00   33.0           2.0        13340.0

             open        high         low       close    volume  ratio_dbuy  \
0      434.489990  435.049988  434.320007  434.320007  412550.0    0.250785
1      434.299988  434.709991  433.850006  433.850006  109232.0    0.493689
2      433.850006  434.399994  433.730011  434.160004  122847.0    0.480586
3      434.179993  434.369995  433.750000  433.799988   82309.0    0.481281
4      433.809998  434.089996  433.720001  433.850006   86827.0    0.609997
...           ...         ...         ...         ...       ...         ...
93425  525.940002  526.440002  525.940002  526.409973   41728.0    0.471466
93426  526.409973  526.630005  526.349976  526.609985   28778.0    0.350453
93427  526.609985  526.780029  526.609985  526.659973   57271.0    0.391810
93428  526.669983  526.919983  526.580017  526.900024   55642.0    0.465503
93429  526.890015  527.010010  526.729980  526.849976  137463.0    0.444601

       ratio_dsell  ratio_neutral         dVol     dVolBuy    dVolSell  \
0         0.198788       0.550426  179338752.0  44975496.0  35650468.0
1         0.464868       0.041442   47442292.0  23421754.0  22054416.0
2         0.451441       0.067973   53323212.0  25626386.0  24072264.0
3         0.486295       0.032423   35722984.0  17192804.0  17371922.0
4         0.325190       0.064813   37673172.0  22980508.0  12250956.0
...            ...            ...          ...         ...         ...
93425     0.350150       0.178384   21959392.0  10353100.0   7689091.0
93426     0.400345       0.249202   15151526.0   5309894.5   6065842.5
93427     0.355937       0.252253   30163432.0  11818339.0  10736282.0
93428     0.265581       0.268916   29309952.0  13643879.0   7784157.0
93429     0.310505       0.244894   72424272.0  32199934.0  22488080.0

         buyVol  sellVol        date      time
0      103461.0  82010.0  2024-02-22  09:31:00
1       53926.0  50778.0  2024-02-22  09:32:00
2       59038.0  55458.0  2024-02-22  09:33:00
3       39613.0  40026.0  2024-02-22  09:34:00
4       52964.0  28235.0  2024-02-22  09:35:00
...         ...      ...         ...       ...
93425   19673.0  14611.0  2025-02-05  15:56:00
93426   10085.0  11521.0  2025-02-05  15:57:00
93427   22439.0  20384.0  2025-02-05  15:58:00
93428   25901.0  14777.0  2025-02-05  15:59:00
93429   61116.0  42682.0  2025-02-05  16:00:00

[93430 rows x 20 columns]

In [ ]:
df_clean_15 = df_clean_15[['ts_event', 'buyVol', 'symbol', 'date', 'time']]

In [ ]:
df_clean_15 = df_clean_15.rename(columns = {'buyVol': 'volume'})

In [ ]:
df_clean_15 = df_clean_15.rename(columns = {'sellVol': 'volume'})

In [18]:
df_clean_15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93430 entries, 0 to 93429
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ts_event  93430 non-null  datetime64[ns, America/New_York]
 1   volume    93430 non-null  float64
 2   symbol    93430 non-null  object
 3   date      93430 non-null  object
 4   time      93430 non-null  object
dtypes: datetime64[ns, America/New_York](1), float64(1), object(3)
memory usage: 3.6+ MB

In [ ]:
# Calculate Daily Stats

daily_Stats_15 = dict()

for sym_name in syms:
    mask = df_clean_15.symbol == sym_name
    temp = df_clean_15[mask]
    daily_vol = temp["volume"].groupby(temp['date']).sum()
    
    daily_log_vol = np.log(daily_vol)
    log_mean = daily_log_vol.rolling(20).mean()
    mean = daily_vol.rolling(20).mean()
    std = daily_vol.rolling(20).std()
    
    df_temp = pd.DataFrame()
    df_temp["daily_vol"] = daily_vol
    df_temp["daily_log_vol"] = daily_log_vol
    df_temp["daily_vol_mean"] = mean
    df_temp["daily_vol_std"] = std
    df_temp["daily_vol_log_mean"] = log_mean
    
    df_temp[["daily_vol_mean","daily_vol_std","daily_vol_log_mean"]] = df_temp[["daily_vol_mean","daily_vol_std","daily_vol_log_mean"]].shift(1)
    
    daily_Stats_15[sym_name] = df_temp

In [ ]:
for sym_name in syms:
    for stat in ["daily_vol","daily_vol_mean","daily_vol_std","daily_vol_log_mean"]:
        df_clean_15.loc[(df_clean_15.symbol == sym_name),stat]= df_clean_15.loc[(df_clean_15.symbol == sym_name),:]["date"].map(daily_Stats_15[sym_name][stat])
        
    mask = df_clean_15.symbol == sym_name
    df_clean_15.loc[mask,"cum_sum_vol"] = df_clean_15.loc[mask,"volume"].groupby(df_clean_15['date']).cumsum()

df_clean_15.loc[: , "cum_vol_prof"] = (df_clean_15["cum_sum_vol"] / df_clean_15["daily_vol"]).astype("float")
df_clean_15.loc[: , "vol_prof"] = (df_clean_15["volume"] / df_clean_15["daily_vol"]).astype("float")

In [ ]:
minutes_Stats_15 = list()

for sym_name in syms:
    mask = df_clean_15.symbol == sym_name
    temp = df_clean_15[mask]
    
    cum_vol_prof_var = temp.groupby('time')["cum_vol_prof"].apply(lambda x :x.rolling(20).var().shift(1))
    vol_prof_mean = temp.groupby('time')["vol_prof"].apply(lambda x :x.rolling(20).mean().shift(1))
    cum_vol_prof_mean =  temp.groupby('time')["cum_vol_prof"].apply(lambda x :x.rolling(20).mean().shift(1))
    
    df_temp = pd.DataFrame()
    df_temp["cum_vol_prof_var"] = cum_vol_prof_var
    df_temp["vol_prof_mean"] = vol_prof_mean
    df_temp["cum_vol_prof_mean"] =  cum_vol_prof_mean
    
    
    minutes_Stats_15.append(df_temp)

In [ ]:
# Calculating the time difference from 9:30, prepare for piecewise linear interpolation
def TimeDiff(time):
    return (datetime.combine(date.min, time) - datetime.combine(date.min, datetime.strptime('09:30', '%H:%M').time())).seconds/60
df_clean_15["time_diff"] = df_clean_15["time"].copy().apply(TimeDiff)

In [366]:
df_clean_15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93430 entries, 0 to 93429
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ts_event            93430 non-null  datetime64[ns, America/New_York]
 1   volume              93430 non-null  float64
 2   symbol              93430 non-null  object
 3   date                93430 non-null  object
 4   time                93430 non-null  object
 5   daily_vol           93430 non-null  float64
 6   daily_vol_mean      85630 non-null  float64
 7   daily_vol_std       85630 non-null  float64
 8   daily_vol_log_mean  85630 non-null  float64
 9   cum_sum_vol         93430 non-null  float64
 10  cum_vol_prof        93430 non-null  float64
 11  vol_prof            93430 non-null  float64
 12  cum_vol_prof_var    85630 non-null  float64
 13  vol_prof_mean       85630 non-null  float64
 14  cum_vol_prof_mean   85630 non-null  float64
 15  time_diff           93430 non-null  float64
dtypes: datetime64[ns, America/New_York](1), float64(12), object(3)
memory usage: 11.4+ MB

In [ ]:
test_df = df_clean_15[df_clean_15["date"] >= pd.to_datetime("2024-10-01").date()]
all_date = list(set(test_df.date))
all_date.sort()
all_time = list(set(test_df.time))
all_time.sort()

In [368]:
test_df

,ts_event,volume,symbol,date,time,daily_vol,daily_vol_mean,daily_vol_std,daily_vol_log_mean,cum_sum_vol,cum_vol_prof,vol_prof,cum_vol_prof_var,vol_prof_mean,cum_vol_prof_mean,time_diff
59637,2024-10-01 09:31:00-04:00,17537.0,QQQ,2024-10-01,09:31:00,3911756.0,3226905.15,870190.086150,14.955220,17537.0,0.004483,0.004483,0.000026,0.010755,0.010755,1.0
59638,2024-10-01 09:32:00-04:00,8388.0,QQQ,2024-10-01,09:32:00,3911756.0,3226905.15,870190.086150,14.955220,25925.0,0.006627,0.002144,0.000041,0.006745,0.017499,2.0
59639,2024-10-01 09:33:00-04:00,28241.0,QQQ,2024-10-01,09:33:00,3911756.0,3226905.15,870190.086150,14.955220,54166.0,0.013847,0.007220,0.000097,0.006174,0.023673,3.0
59640,2024-10-01 09:34:00-04:00,35946.0,QQQ,2024-10-01,09:34:00,3911756.0,3226905.15,870190.086150,14.955220,90112.0,0.023036,0.009189,0.000133,0.005582,0.029255,4.0
59641,2024-10-01 09:35:00-04:00,26228.0,QQQ,2024-10-01,09:35:00,3911756.0,3226905.15,870190.086150,14.955220,116340.0,0.029741,0.006705,0.000194,0.006965,0.036221,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93425,2025-02-05 15:56:00-05:00,14611.0,QQQ,2025-02-05,15:56:00,1534087.0,2384081.25,664560.248266,14.646532,1444723.0,0.941748,0.009524,0.000584,0.011725,0.928683,386.0
93426,2025-02-05 15:57:00-05:00,11521.0,QQQ,2025-02-05,15:57:00,1534087.0,2384081.25,664560.248266,14.646532,1456244.0,0.949258,0.007510,0.000425,0.008134,0.936817,387.0
93427,2025-02-05 15:58:00-05:00,20384.0,QQQ,2025-02-05,15:58:00,1534087.0,2384081.25,664560.248266,14.646532,1476628.0,0.962545,0.013287,0.000314,0.009028,0.945845,388.0
93428,2025-02-05 15:59:00-05:00,14777.0,QQQ,2025-02-05,15:59:00,1534087.0,2384081.25,664560.248266,14.646532,1491405.0,0.972178,0.009632,0.000250,0.012083,0.957928,389.0
93429,2025-02-05 16:00:00-05:00,42682.0,QQQ,2025-02-05,16:00:00,1534087.0,2384081.25,664560.248266,14.646532,1534087.0,1.000000,0.027822,0.000000,0.042072,1.000000,390.0

                       ts_event   volume symbol        date      time  \
59637 2024-10-01 09:31:00-04:00  17537.0    QQQ  2024-10-01  09:31:00
59638 2024-10-01 09:32:00-04:00   8388.0    QQQ  2024-10-01  09:32:00
59639 2024-10-01 09:33:00-04:00  28241.0    QQQ  2024-10-01  09:33:00
59640 2024-10-01 09:34:00-04:00  35946.0    QQQ  2024-10-01  09:34:00
59641 2024-10-01 09:35:00-04:00  26228.0    QQQ  2024-10-01  09:35:00
...                         ...      ...    ...         ...       ...
93425 2025-02-05 15:56:00-05:00  14611.0    QQQ  2025-02-05  15:56:00
93426 2025-02-05 15:57:00-05:00  11521.0    QQQ  2025-02-05  15:57:00
93427 2025-02-05 15:58:00-05:00  20384.0    QQQ  2025-02-05  15:58:00
93428 2025-02-05 15:59:00-05:00  14777.0    QQQ  2025-02-05  15:59:00
93429 2025-02-05 16:00:00-05:00  42682.0    QQQ  2025-02-05  16:00:00

       daily_vol  daily_vol_mean  daily_vol_std  daily_vol_log_mean  \
59637  3911756.0      3226905.15  870190.086150           14.955220
59638  3911756.0      3226905.15  870190.086150           14.955220
59639  3911756.0      3226905.15  870190.086150           14.955220
59640  3911756.0      3226905.15  870190.086150           14.955220
59641  3911756.0      3226905.15  870190.086150           14.955220
...          ...             ...            ...                 ...
93425  1534087.0      2384081.25  664560.248266           14.646532
93426  1534087.0      2384081.25  664560.248266           14.646532
93427  1534087.0      2384081.25  664560.248266           14.646532
93428  1534087.0      2384081.25  664560.248266           14.646532
93429  1534087.0      2384081.25  664560.248266           14.646532

       cum_sum_vol  cum_vol_prof  vol_prof  cum_vol_prof_var  vol_prof_mean  \
59637      17537.0      0.004483  0.004483          0.000026       0.010755
59638      25925.0      0.006627  0.002144          0.000041       0.006745
59639      54166.0      0.013847  0.007220          0.000097       0.006174
59640      90112.0      0.023036  0.009189          0.000133       0.005582
59641     116340.0      0.029741  0.006705          0.000194       0.006965
...            ...           ...       ...               ...            ...
93425    1444723.0      0.941748  0.009524          0.000584       0.011725
93426    1456244.0      0.949258  0.007510          0.000425       0.008134
93427    1476628.0      0.962545  0.013287          0.000314       0.009028
93428    1491405.0      0.972178  0.009632          0.000250       0.012083
93429    1534087.0      1.000000  0.027822          0.000000       0.042072

       cum_vol_prof_mean  time_diff
59637           0.010755        1.0
59638           0.017499        2.0
59639           0.023673        3.0
59640           0.029255        4.0
59641           0.036221        5.0
...                  ...        ...
93425           0.928683      386.0
93426           0.936817      387.0
93427           0.945845      388.0
93428           0.957928      389.0
93429           1.000000      390.0

[33793 rows x 16 columns]

In [ ]:
def Kalman(df, sym):
    
    for date in all_date[20:]:
        
        mask0 = (df["date"] == date) & (df["time"] == datetime.strptime('09:31', '%H:%M').time())
        temp = df.loc[mask0,:]
        ADV = temp.daily_vol_mean.values
        P0 = temp.daily_vol_std.values ** 2
        x0 = ADV
        print(date)
             
        
        for t in all_time:
   
            mask1 = ((df["date"] == date) & (df["time"] == t))
            temp2 = df[mask1]
            y = temp2.cum_sum_vol.values
            
            if t == datetime.strptime('9:31', '%H:%M').time():
                P = P0
                x = x0
                last_pred = ADV
                
            u = temp2.vol_prof_mean.values
            miu = temp2.cum_vol_prof_mean.values
            R = ADV**2 * temp2.cum_vol_prof_var.values
            K = (miu * P) / (miu ** 2 * P + R)
            P = (1 - K*miu) * P
            x = x + K * (y - miu*x)
            
            try:
                df.loc[mask1, "K_pred_vol"] = np.array(x).flatten()
                df.loc[mask1, "K_pred_interval_vol"] = last_pred * u
                last_pred = x

            except:
                print(x)


    return df

In [370]:
Kalman_dict_15 = dict()

for sym_name in syms:
    
    Kalman_dict_15[sym_name] = Kalman(test_df,sym_name)
    

Kalman_dict_15

2024-10-29


2024-10-30
2024-10-31
2024-11-01
2024-11-04
2024-11-05
2024-11-06
2024-11-07
2024-11-08
2024-11-11
2024-11-12
2024-11-13
2024-11-14
2024-11-15
2024-11-18
2024-11-19
2024-11-20
2024-11-21
2024-11-22
2024-11-25
2024-11-26
2024-11-27
2024-11-29
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
2024-12-02
2024-12-03
2024-12-04
2024-12-05
2024-12-06
2024-12-09
2024-12-10
2024-12-11
2024-12-12
2024-12-13
2024-12-16
2024-12-17
2024-12-18
2024-12-19
2024-12-20
2024-12-23
2024-12-24
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
2024-12-26
2024-12-27
2024-12-30
2024-12-31
2025-01-02
2025-01-03
2025-01-06
2025-01-07
2025-01-08
2025-01-10
2025-01-13
2025-01-14
2025-01-15
2025-01-16
2025-01-17
2025-01-21
2025-01-22
2025-01-23
2025-01-24
2025-01-27
2025-01-28
2025-01-29
2025-01-30
2025-01-31
2025-02-03
2025-02-04
2025-02-05

/var/folders/r5/gdkshdms0970h1kdrr8n5m1r0000gn/T/ipykernel_67770/2520986495.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[mask1, "K_pred_vol"] = np.array(x).flatten()
/var/folders/r5/gdkshdms0970h1kdrr8n5m1r0000gn/T/ipykernel_67770/2520986495.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[mask1, "K_pred_interval_vol"] = last_pred * u

{'QQQ':                        ts_event   volume symbol        date      time  \
 59637 2024-10-01 09:31:00-04:00  17537.0    QQQ  2024-10-01  09:31:00
 59638 2024-10-01 09:32:00-04:00   8388.0    QQQ  2024-10-01  09:32:00
 59639 2024-10-01 09:33:00-04:00  28241.0    QQQ  2024-10-01  09:33:00
 59640 2024-10-01 09:34:00-04:00  35946.0    QQQ  2024-10-01  09:34:00
 59641 2024-10-01 09:35:00-04:00  26228.0    QQQ  2024-10-01  09:35:00
 ...                         ...      ...    ...         ...       ...
 93425 2025-02-05 15:56:00-05:00  14611.0    QQQ  2025-02-05  15:56:00
 93426 2025-02-05 15:57:00-05:00  11521.0    QQQ  2025-02-05  15:57:00
 93427 2025-02-05 15:58:00-05:00  20384.0    QQQ  2025-02-05  15:58:00
 93428 2025-02-05 15:59:00-05:00  14777.0    QQQ  2025-02-05  15:59:00
 93429 2025-02-05 16:00:00-05:00  42682.0    QQQ  2025-02-05  16:00:00

        daily_vol  daily_vol_mean  daily_vol_std  daily_vol_log_mean  \
 59637  3911756.0      3226905.15  870190.086150           14.955220
 59638  3911756.0      3226905.15  870190.086150           14.955220
 59639  3911756.0      3226905.15  870190.086150           14.955220
 59640  3911756.0      3226905.15  870190.086150           14.955220
 59641  3911756.0      3226905.15  870190.086150           14.955220
 ...          ...             ...            ...                 ...
 93425  1534087.0      2384081.25  664560.248266           14.646532
 93426  1534087.0      2384081.25  664560.248266           14.646532
 93427  1534087.0      2384081.25  664560.248266           14.646532
 93428  1534087.0      2384081.25  664560.248266           14.646532
 93429  1534087.0      2384081.25  664560.248266           14.646532

        cum_sum_vol  cum_vol_prof  vol_prof  cum_vol_prof_var  vol_prof_mean  \
 59637      17537.0      0.004483  0.004483          0.000026       0.010755
 59638      25925.0      0.006627  0.002144          0.000041       0.006745
 59639      54166.0      0.013847  0.007220          0.000097       0.006174
 59640      90112.0      0.023036  0.009189          0.000133       0.005582
 59641     116340.0      0.029741  0.006705          0.000194       0.006965
 ...            ...           ...       ...               ...            ...
 93425    1444723.0      0.941748  0.009524          0.000584       0.011725
 93426    1456244.0      0.949258  0.007510          0.000425       0.008134
 93427    1476628.0      0.962545  0.013287          0.000314       0.009028
 93428    1491405.0      0.972178  0.009632          0.000250       0.012083
 93429    1534087.0      1.000000  0.027822          0.000000       0.042072

        cum_vol_prof_mean  time_diff    K_pred_vol  K_pred_interval_vol
 59637           0.010755        1.0           NaN                  NaN
 59638           0.017499        2.0           NaN                  NaN
 59639           0.023673        3.0           NaN                  NaN
 59640           0.029255        4.0           NaN                  NaN
 59641           0.036221        5.0           NaN                  NaN
 ...                  ...        ...           ...                  ...
 93425           0.928683      386.0  1.642077e+06         19284.897334
 93426           0.936817      387.0  1.638562e+06         13356.085211
 93427           0.945845      388.0  1.634503e+06         14793.093892
 93428           0.957928      389.0  1.629585e+06         19749.696417
 93429           1.000000      390.0  1.534087e+06         68560.168455

 [33793 rows x 18 columns]}

In [371]:
Kalman_dict_15

{'QQQ':                        ts_event   volume symbol        date      time  \
 59637 2024-10-01 09:31:00-04:00  17537.0    QQQ  2024-10-01  09:31:00
 59638 2024-10-01 09:32:00-04:00   8388.0    QQQ  2024-10-01  09:32:00
 59639 2024-10-01 09:33:00-04:00  28241.0    QQQ  2024-10-01  09:33:00
 59640 2024-10-01 09:34:00-04:00  35946.0    QQQ  2024-10-01  09:34:00
 59641 2024-10-01 09:35:00-04:00  26228.0    QQQ  2024-10-01  09:35:00
 ...                         ...      ...    ...         ...       ...
 93425 2025-02-05 15:56:00-05:00  14611.0    QQQ  2025-02-05  15:56:00
 93426 2025-02-05 15:57:00-05:00  11521.0    QQQ  2025-02-05  15:57:00
 93427 2025-02-05 15:58:00-05:00  20384.0    QQQ  2025-02-05  15:58:00
 93428 2025-02-05 15:59:00-05:00  14777.0    QQQ  2025-02-05  15:59:00
 93429 2025-02-05 16:00:00-05:00  42682.0    QQQ  2025-02-05  16:00:00

        daily_vol  daily_vol_mean  daily_vol_std  daily_vol_log_mean  \
 59637  3911756.0      3226905.15  870190.086150           14.955220
 59638  3911756.0      3226905.15  870190.086150           14.955220
 59639  3911756.0      3226905.15  870190.086150           14.955220
 59640  3911756.0      3226905.15  870190.086150           14.955220
 59641  3911756.0      3226905.15  870190.086150           14.955220
 ...          ...             ...            ...                 ...
 93425  1534087.0      2384081.25  664560.248266           14.646532
 93426  1534087.0      2384081.25  664560.248266           14.646532
 93427  1534087.0      2384081.25  664560.248266           14.646532
 93428  1534087.0      2384081.25  664560.248266           14.646532
 93429  1534087.0      2384081.25  664560.248266           14.646532

        cum_sum_vol  cum_vol_prof  vol_prof  cum_vol_prof_var  vol_prof_mean  \
 59637      17537.0      0.004483  0.004483          0.000026       0.010755
 59638      25925.0      0.006627  0.002144          0.000041       0.006745
 59639      54166.0      0.013847  0.007220          0.000097       0.006174
 59640      90112.0      0.023036  0.009189          0.000133       0.005582
 59641     116340.0      0.029741  0.006705          0.000194       0.006965
 ...            ...           ...       ...               ...            ...
 93425    1444723.0      0.941748  0.009524          0.000584       0.011725
 93426    1456244.0      0.949258  0.007510          0.000425       0.008134
 93427    1476628.0      0.962545  0.013287          0.000314       0.009028
 93428    1491405.0      0.972178  0.009632          0.000250       0.012083
 93429    1534087.0      1.000000  0.027822          0.000000       0.042072

        cum_vol_prof_mean  time_diff    K_pred_vol  K_pred_interval_vol
 59637           0.010755        1.0           NaN                  NaN
 59638           0.017499        2.0           NaN                  NaN
 59639           0.023673        3.0           NaN                  NaN
 59640           0.029255        4.0           NaN                  NaN
 59641           0.036221        5.0           NaN                  NaN
 ...                  ...        ...           ...                  ...
 93425           0.928683      386.0  1.642077e+06         19284.897334
 93426           0.936817      387.0  1.638562e+06         13356.085211
 93427           0.945845      388.0  1.634503e+06         14793.093892
 93428           0.957928      389.0  1.629585e+06         19749.696417
 93429           1.000000      390.0  1.534087e+06         68560.168455

 [33793 rows x 18 columns]}

In [372]:
Kalman_dict_15['QQQ'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33793 entries, 59637 to 93429
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ts_event             33793 non-null  datetime64[ns, America/New_York]
 1   volume               33793 non-null  float64
 2   symbol               33793 non-null  object
 3   date                 33793 non-null  object
 4   time                 33793 non-null  object
 5   daily_vol            33793 non-null  float64
 6   daily_vol_mean       33793 non-null  float64
 7   daily_vol_std        33793 non-null  float64
 8   daily_vol_log_mean   33793 non-null  float64
 9   cum_sum_vol          33793 non-null  float64
 10  cum_vol_prof         33793 non-null  float64
 11  vol_prof             33793 non-null  float64
 12  cum_vol_prof_var     33793 non-null  float64
 13  vol_prof_mean        33793 non-null  float64
 14  cum_vol_prof_mean    33793 non-null  float64
 15  time_diff            33793 non-null  float64
 16  K_pred_vol           25812 non-null  float64
 17  K_pred_interval_vol  25812 non-null  float64
dtypes: datetime64[ns, America/New_York](1), float64(14), object(3)
memory usage: 4.9+ MB

In [373]:
for sym_name in syms:

    temp = Kalman_dict_15[sym_name].dropna().set_index("ts_event")
    temp.index = temp.index.to_series().apply(lambda x: x.strftime('%Y-%m-%d %H:%M'))
    index = random.randrange(0,len(temp)-5*26)
    """
    ax = temp[["K_pred_vol","cum_sum_vol","daily_vol","daily_vol_mean"]].plot(figsize = (18, 8),title = sym_name + " 15-min")
    ax.set_xlabel("Time")
    ax.set_ylabel("Volume")
    """
    rand_temp = temp.iloc[index:index+5*26]
    """
    ax = rand_temp[["K_pred_vol","cum_sum_vol","daily_vol","daily_vol_mean"]].plot(figsize = (18, 8),title = sym_name+ " 15-min")
    ax.set_xlabel("Time")
    ax.set_ylabel("Volume")
    """
    fig, ax = plt.subplots(figsize=(18,8))
    ax.scatter(rand_temp.index, rand_temp["K_pred_interval_vol"],label= "K_pred_interval_vol")
    ax.scatter(rand_temp.index, rand_temp["volume"],label= "realized volume")
    xpositions = rand_temp[rand_temp.time==datetime.strptime('09:45', '%H:%M').time()].index.values
    for xc in xpositions:
        plt.axvline(x=xc, color='k', linestyle='--')
    ax.set_xticks(rand_temp.index[::26])
    ax.set_title(sym_name + " 15-min" + " Intrady volume distribution")
    ax.set_xlabel("Time")
    ax.set_ylabel("Volume")
    plt.legend()
    plt.show()

In [374]:
Kalman_dict_15['QQQ'][['symbol', 'ts_event', 'volume', 'K_pred_interval_vol']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33793 entries, 59637 to 93429
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   symbol               33793 non-null  object
 1   ts_event             33793 non-null  datetime64[ns, America/New_York]
 2   volume               33793 non-null  float64
 3   K_pred_interval_vol  25812 non-null  float64
dtypes: datetime64[ns, America/New_York](1), float64(2), object(1)
memory usage: 1.3+ MB

In [ ]:
temp = Kalman_dict_15['QQQ'][['symbol', 'ts_event', 'volume', 'K_pred_interval_vol']]
temp = temp.rename(columns = {'volume' : 'sell_volume', 'K_pred_interval_vol' : 'K_pred_interval_vol_sell'})

output = pd.merge(output, temp, on = ['symbol', 'ts_event'], how = 'left')

In [ ]:
output.to_csv('QQQ_kalman_buy_sell_prediction_1min.csv')

In [ ]:
output = Kalman_dict_15['QQQ'][['symbol', 'ts_event', 'volume', 'K_pred_interval_vol']]

In [ ]:
output = output.rename(columns = {'volume' : 'buy_volume', 'K_pred_interval_vol' : 'K_pred_interval_vol_buy'})

In [146]:
output.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33756 entries, 59626 to 93381
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   symbol                   33756 non-null  object
 1   ts_event                 33756 non-null  datetime64[ns, America/New_York]
 2   buy_volume               33756 non-null  float64
 3   K_pred_interval_vol_buy  25812 non-null  float64
dtypes: datetime64[ns, America/New_York](1), float64(2), object(1)
memory usage: 1.3+ MB

In [ ]:
Kalman_dict_15['SPY'][['symbol', 'ts_event', 'volume', 'K_pred_interval_vol']].to_csv('SPY_kalman_prediction_1min.csv')

In [72]:
Kalman_dict_15['QQQ'][['symbol', 'ts_event', 'volume', 'K_pred_interval_vol']]

,symbol,ts_event,volume,K_pred_interval_vol
366638,QQQ,2024-10-01 09:31:00-04:00,144252.0,NaN
366639,QQQ,2024-10-01 09:32:00-04:00,24161.0,NaN
366640,QQQ,2024-10-01 09:33:00-04:00,56286.0,NaN
366641,QQQ,2024-10-01 09:34:00-04:00,86728.0,NaN
366642,QQQ,2024-10-01 09:35:00-04:00,55186.0,NaN
...,...,...,...,...
400426,QQQ,2025-02-05 15:56:00-05:00,41728.0,42882.896997
400427,QQQ,2025-02-05 15:57:00-05:00,28778.0,30039.334040
400428,QQQ,2025-02-05 15:58:00-05:00,57271.0,33625.002526
400429,QQQ,2025-02-05 15:59:00-05:00,55642.0,46965.464285
400430,QQQ,2025-02-05 16:00:00-05:00,137463.0,162893.014184

       symbol                  ts_event    volume  K_pred_interval_vol
366638    QQQ 2024-10-01 09:31:00-04:00  144252.0                  NaN
366639    QQQ 2024-10-01 09:32:00-04:00   24161.0                  NaN
366640    QQQ 2024-10-01 09:33:00-04:00   56286.0                  NaN
366641    QQQ 2024-10-01 09:34:00-04:00   86728.0                  NaN
366642    QQQ 2024-10-01 09:35:00-04:00   55186.0                  NaN
...       ...                       ...       ...                  ...
400426    QQQ 2025-02-05 15:56:00-05:00   41728.0         42882.896997
400427    QQQ 2025-02-05 15:57:00-05:00   28778.0         30039.334040
400428    QQQ 2025-02-05 15:58:00-05:00   57271.0         33625.002526
400429    QQQ 2025-02-05 15:59:00-05:00   55642.0         46965.464285
400430    QQQ 2025-02-05 16:00:00-05:00  137463.0        162893.014184

[33793 rows x 4 columns]

In [ ]:
def Errors(df):
    result = pd.DataFrame(columns=["symbol","direction","MAE","MAPE"])

    dir = ['buy', 'sell']

    for d in dir:
        target = d + '_volume'
        y_head = d + '_mean'
        mae = np.mean(abs(df[target] - df[y_head]))
        mape = np.mean(abs(df[target] - df[y_head]))/ np.mean(df[target])

        result = result.append({"symbol": 'QQQ', "direction": d, "method":'mean', "MAE": mae, "MAPE": mape}, ignore_index = True)

        y_head = 'K_pred_interval_vol_' + d

        mae = np.mean(abs(df[target] - df[y_head]))
        mape = np.mean(abs(df[target] - df[y_head]))/ np.mean(df[target])
    
        result = result.append({"symbol": 'QQQ', "direction": d, "method":'kalman_filter', "MAE": mae, "MAPE": mape}, ignore_index = True)
    
    return result